FROM guneysu/nginx:latest
ADD nginx.conf /etc/nginx/nginx.conf
ADD https://raw.githubusercontent.com/ojs/ojs-docker/master/vhost.conf /etc/nginx/sites-enabled/
ADD https://github.com/ojs/ojs-docker/raw/master/sites/default /etc/nginx/sites-enabled/default.conf
